### ISSUE TITLE
aplayer+meting添加播放列表 | 陈科衡的博客

### ISSUE THREAD

**Issue by can-dy-jack** [can-dy-jack/ckh.github.io#12]
https://kartjim.top/music/aplayer-meting%E6%B7%BB%E5%8A%A0%E6%92%AD%E6%94%BE%E5%88%97%E8%A1%A8/#more 

 aplayer+meting添加播放列表看官网aplayer中文文档MetingJS 使用 hexo-tag-aplayer 插件在博客根目录下执行 1$ npm install --save hexo-tag-aplayer 下载hexo-tag-aplayer插件 使用：

**Comment by kartjim** [comment]
## music
