### ISSUE TITLE
文章摘要 | 陈科衡的博客

### ISSUE THREAD

**Issue by can-dy-jack** [can-dy-jack/ckh.github.io#2]
https://kartjim.top/all/%E6%96%87%E7%AB%A0%E6%91%98%E8%A6%81/ 

 文章摘要:在需要显示摘要的地方添加如下代码即可： 以上是摘要<!–more–>以下是余下全文  more以上内容即是文章摘要，在主页显示，more以下内容点击『 more >> 』链接打开全文才显示。

**Comment by can-dy-jack** [comment]
# 我的博客第一条评论！！！

**Comment by Moriafly** [comment]
不错不错！变亮了
